# Generated by Django 5.0.2 on 2024-03-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_num', models.IntegerField(unique=True)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
